services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/postgres
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: changemeinprod!
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/postgres
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: changemeinprod!
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data1:
